"use client";
import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
type User={userId:number;username:string;name:string};
type Voucher={voucher_id:number;voucher_date:string;payee:string;amount:string;amount_in_words:string;type_of_payee:string;custom_payee_type:string|null;mode_of_payment:string;towards:string;payee_pan:string|null;tds:string|null;created_by_name:string;created_by_username:string};
type Props={user:User};
const PAYEE_TYPES=["Site expenses","Concreting","Steel","Sand","Jelly","Cement","Civil","Plumbing","Tile laying","Electrical","Carpenter","UPVC","Custom"];
const PAYMENT_MODES=["Cash","Cheque","DD","RTGS","UPI"];
function formatDate(v:string){const s=String(v||"").split("T")[0];const p=s.split("-");return p.length===3?`${p[2]}-${p[1]}-${p[0]}`:"-";}
export default function VouchersPageClient({user}:Props){const router=useRouter();const [vouchers,setVouchers]=useState<Voucher[]>([]);const [selected,setSelected]=useState<number[]>([]);const [search,setSearch]=useState("");const [from,setFrom]=useState("");const [to,setTo]=useState("");const [type,setType]=useState("");const [mode,setMode]=useState("");const [loading,setLoading]=useState(true);const [downloading,setDownloading]=useState(false);const [error,setError]=useState("");
async function loadVouchersWithFilters(s:string,f:string,t:string,ty:string,m:string){setLoading(true);setError("");try{const p=new URLSearchParams();if(s.trim())p.set("search",s.trim());if(f)p.set("from",f);if(t)p.set("to",t);if(ty)p.set("type",ty);if(m)p.set("mode",m);const r=await fetch(p.toString()?`/api/vouchers?${p}`:"/api/vouchers");const d=await r.json();if(!r.ok){setError(d?.error||d?.message||"Unable to load vouchers.");return [];}const rows=d.vouchers||[];setVouchers(rows);setSelected([]);return rows;}catch{setError("Unable to connect to the server.");return [];}finally{setLoading(false);}}
async function loadVouchers(){await loadVouchersWithFilters(search,from,to,type,mode);}
useEffect(()=>{loadVouchersWithFilters("","","","","");},[]);
function toggle(id:number){setSelected(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id]);}
function toggleAll(){setSelected(selected.length===vouchers.length?vouchers.map(v=>v.voucher_id):vouchers.map(v=>v.voucher_id));}
async function clear(){setSearch("");setFrom("");setTo("");setType("");setMode("");await loadVouchersWithFilters("","","","","");}
async function downloadIds(ids:number[]){if(!ids.length)return;setDownloading(true);setError("");try{const r=await fetch('/api/vouchers/pdf',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({voucherIds:ids})});if(!r.ok){const d=await r.json().catch(()=>null);throw new Error(d?.message||d?.error||'Unable to generate PDF.');}const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='payment-vouchers.pdf';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}catch(e){setError(e instanceof Error?e.message:'Unable to download vouchers.');}finally{setDownloading(false);}}
async function downloadDateRange(){if(!from&&!to){setError('Please select a date range first.');return;}setDownloading(true);setError("");try{const p=new URLSearchParams();if(from)p.set('from',from);if(to)p.set('to',to);const r=await fetch(`/api/vouchers?${p}`);const d=await r.json();if(!r.ok)throw new Error(d?.error||d?.message||'Unable to fetch vouchers for the selected date range.');const ids=(d.vouchers||[]).map((v:Voucher)=>v.voucher_id);if(!ids.length)throw new Error('No vouchers found for the selected date range.');const pdf=await fetch('/api/vouchers/pdf',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({voucherIds:ids})});if(!pdf.ok){const x=await pdf.json().catch(()=>null);throw new Error(x?.message||x?.error||'Unable to generate PDF.');}const blob=await pdf.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='payment-vouchers.pdf';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}catch(e){setError(e instanceof Error?e.message:'Unable to download vouchers.');}finally{setDownloading(false);}}
return <main className="lux-page"><header className="lux-header"><div className="lux-shell flex items-center justify-between py-4"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#101827] text-sm font-bold text-[#d8c29a]">PV</div><div><p className="text-[10px] uppercase tracking-[.24em] text-[#b8955a]">Payment Voucher</p><p className="lux-serif text-lg">Voucher Register</p></div></div><div className="flex items-center gap-3"><div className="hidden text-right sm:block"><p className="text-sm font-semibold">{user.name}</p><p className="text-xs text-slate-500">@{user.username}</p></div><button className="lux-secondary px-4 py-2.5 text-sm" onClick={()=>router.push('/dashboard')}>Dashboard</button></div></div></header><div className="lux-shell py-8 sm:py-10"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-[11px] font-semibold uppercase tracking-[.28em] text-[#b8955a]">Payment records</p><h1 className="lux-serif mt-2 text-4xl">Vouchers</h1><p className="mt-2 text-sm text-slate-500">Search, filter and download payment vouchers.</p></div><button className="lux-primary" onClick={()=>router.push('/vouchers/create')}>+ Create Voucher</button></div>
<div className="lux-card mt-8 p-5"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-5"><div className="lg:col-span-2"><label className="mb-2 block text-xs font-semibold uppercase tracking-wider text-slate-500">Search</label><input className="lux-input" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')loadVouchers()}} placeholder="Paid to, towards or amount…"/></div><div><label className="mb-2 block text-xs font-semibold uppercase tracking-wider text-slate-500">From</label><input className="lux-input" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></div><div><label className="mb-2 block text-xs font-semibold uppercase tracking-wider text-slate-500">To</label><input className="lux-input" type="date" value={to} onChange={e=>setTo(e.target.value)}/></div><div><label className="mb-2 block text-xs font-semibold uppercase tracking-wider text-slate-500">Payee Type</label><select className="lux-input" value={type} onChange={e=>setType(e.target.value)}><option value="">All types</option>{PAYEE_TYPES.map(x=><option key={x}>{x}</option>)}</select></div></div><div className="mt-4 flex flex-wrap gap-3"><select className="lux-input max-w-xs" value={mode} onChange={e=>setMode(e.target.value)}><option value="">All payment modes</option>{PAYMENT_MODES.map(x=><option key={x}>{x}</option>)}</select><button className="lux-primary" disabled={loading} onClick={loadVouchers}>{loading?'Loading…':'Search'}</button><button className="lux-secondary" disabled={loading} onClick={clear}>Clear</button></div></div>
<div className="mt-5 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-500"><span className="font-semibold text-slate-800">{vouchers.length}</span> voucher{vouchers.length===1?'':'s'} found</p><div className="flex flex-wrap gap-3"><button className="lux-secondary" disabled={!selected.length||downloading} onClick={()=>downloadIds(selected)}>{downloading?'Generating…':`Download Selected (${selected.length})`}</button><button className="lux-primary" disabled={downloading||(!from&&!to)} onClick={downloadDateRange}>{downloading?'Generating…':'Download Date Range'}</button></div></div>{error&&<div className="mt-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
<div className="lux-card mt-5 overflow-hidden">{loading?<div className="px-6 py-16 text-center text-sm text-slate-500">Loading vouchers…</div>:!vouchers.length?<div className="px-6 py-16 text-center"><p className="lux-serif text-2xl">No vouchers found</p><p className="mt-2 text-sm text-slate-500">Try changing your search or filters.</p></div>:<div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="border-b border-[#e6e0d5] bg-[#fbf8f1]"><tr><th className="w-12 px-4 py-4"><input type="checkbox" checked={selected.length===vouchers.length&&vouchers.length>0} onChange={toggleAll}/></th>{['Voucher','Date','Paid To','Type','Towards','Amount','Mode','Created By','Action'].map(h=><th key={h} className="px-4 py-4 text-xs font-semibold uppercase tracking-wider text-slate-500">{h}</th>)}</tr></thead><tbody className="divide-y divide-[#eee9df]">{vouchers.map(v=><tr key={v.voucher_id} className="hover:bg-[#fffdf8]"><td className="px-4 py-4"><input type="checkbox" checked={selected.includes(v.voucher_id)} onChange={()=>toggle(v.voucher_id)}/></td><td className="px-4 py-4 font-semibold text-[#101827]">#{v.voucher_id}</td><td className="whitespace-nowrap px-4 py-4 text-slate-600">{formatDate(v.voucher_date)}</td><td className="px-4 py-4 font-semibold">{v.payee}</td><td className="px-4 py-4 text-slate-600">{v.type_of_payee==='Custom'?v.custom_payee_type:v.type_of_payee}</td><td className="max-w-xs px-4 py-4 text-slate-600"><span className="block truncate" title={v.towards}>{v.towards}</span></td><td className="whitespace-nowrap px-4 py-4 font-semibold">₹ {Number(v.amount).toLocaleString('en-IN',{minimumFractionDigits:2})}</td><td className="px-4 py-4"><span className="rounded-full border border-[#e6e0d5] bg-[#fbf8f1] px-3 py-1 text-xs font-semibold">{v.mode_of_payment}</span></td><td className="px-4 py-4 text-slate-600">{v.created_by_name}</td><td className="px-4 py-4 text-right"><a className="lux-link text-sm" href={`/api/vouchers/${v.voucher_id}/pdf`}>PDF</a></td></tr>)}</tbody></table></div>}</div></div></main>}
