import { NextRequest, NextResponse } from "next/server";
import { sql } from "@/lib/db";
import { getSession } from "@/lib/session";
async function idOf(p:Promise<{id:string}>){const {id}=await p;const n=Number(id);return Number.isInteger(n)&&n>0?n:null}
function parse(b:any){return{voucherDate:String(b?.voucherDate??'').trim(),payee:String(b?.payee??'').trim(),amount:Number(b?.amount),amountInWords:String(b?.amountInWords??'').trim(),typeOfPayee:String(b?.typeOfPayee??'').trim(),customPayeeType:b?.customPayeeType==null?null:String(b.customPayeeType).trim(),modeOfPayment:String(b?.modeOfPayment??'').trim(),towards:String(b?.towards??'').trim(),payeePan:b?.payeePan?String(b.payeePan).trim():null,tds:b?.tds?String(b.tds).trim():null,allowDuplicate:b?.allowDuplicate===true}}
function validate(d:any){if(!d.voucherDate)return'Date is required.';if(!d.payee)return'Paid To is required.';if(!Number.isFinite(d.amount)||d.amount<=0)return'Please enter a valid amount.';if(!d.amountInWords)return'Amount in words is required.';if(!d.typeOfPayee)return'Type of payee is required.';if(d.typeOfPayee==='Custom'&&!d.customPayeeType)return'Custom payee type is required.';if(!d.modeOfPayment)return'Mode of payment is required.';if(!d.towards)return'Towards is required.';return null}
export async function GET(_r:NextRequest,{params}:{params:Promise<{id:string}>}){try{const s=await getSession();if(!s)return NextResponse.json({message:'Unauthorized'},{status:401});const id=await idOf(params);if(id===null)return NextResponse.json({message:'Invalid voucher ID.'},{status:400});const rows=await sql`SELECT voucher_id,created_by,payee,amount,amount_in_words,type_of_payee,custom_payee_type,mode_of_payment,towards,payee_pan,tds,voucher_date,created_at,updated_at,deleted_at FROM vouchers WHERE voucher_id=${id} AND created_by=${s.userId} LIMIT 1`;if(!rows.length)return NextResponse.json({message:'Voucher not found.'},{status:404});return NextResponse.json({success:true,voucher:rows[0]})}catch(e){console.error(e);return NextResponse.json({message:'Unable to fetch voucher.'},{status:500})}}
export async function PUT(req:NextRequest,{params}:{params:Promise<{id:string}>}){try{const s=await getSession();if(!s)return NextResponse.json({message:'Unauthorized'},{status:401});const id=await idOf(params);if(id===null)return NextResponse.json({message:'Invalid voucher ID.'},{status:400});const d=parse(await req.json()),err=validate(d);if(err)return NextResponse.json({message:err},{status:400});if(!d.allowDuplicate){const dup=await sql`SELECT voucher_id FROM vouchers WHERE created_by=${s.userId} AND deleted_at IS NULL AND voucher_id<>${id} AND voucher_date=${d.voucherDate} AND LOWER(BTRIM(payee))=LOWER(BTRIM(${d.payee})) AND amount=${d.amount} AND LOWER(BTRIM(towards))=LOWER(BTRIM(${d.towards})) LIMIT 1`;if(dup.length)return NextResponse.json({message:`A similar voucher already exists: #${dup[0].voucher_id}. Save anyway if this is intentional.`,duplicate:dup[0]},{status:409})}await sql`INSERT INTO payees(payee_name) VALUES(${d.payee}) ON CONFLICT DO NOTHING`;const rows=await sql`UPDATE vouchers SET payee=${d.payee},amount=${d.amount},amount_in_words=${d.amountInWords},type_of_payee=${d.typeOfPayee},custom_payee_type=${d.typeOfPayee==='Custom'?d.customPayeeType:null},mode_of_payment=${d.modeOfPayment},towards=${d.towards},payee_pan=${d.payeePan},tds=${d.tds},voucher_date=${d.voucherDate},updated_at=NOW() WHERE voucher_id=${id} AND created_by=${s.userId} AND deleted_at IS NULL RETURNING *`;if(!rows.length)return NextResponse.json({message:'Voucher not found.'},{status:404});return NextResponse.json({success:true,voucher:rows[0]})}catch(e){console.error(e);return NextResponse.json({message:'Unable to update voucher.'},{status:500})}}
export async function DELETE(_r:NextRequest,{params}:{params:Promise<{id:string}>}){try{const s=await getSession();if(!s)return NextResponse.json({message:'Unauthorized'},{status:401});const id=await idOf(params);if(id===null)return NextResponse.json({message:'Invalid voucher ID.'},{status:400});const rows=await sql`UPDATE vouchers SET deleted_at=NOW(),deleted_by=${s.userId},updated_at=NOW() WHERE voucher_id=${id} AND created_by=${s.userId} AND deleted_at IS NULL RETURNING voucher_id`;if(!rows.length)return NextResponse.json({message:'Voucher not found.'},{status:404});return NextResponse.json({success:true,voucherId:Number(rows[0].voucher_id)})}catch(e){console.error(e);return NextResponse.json({message:'Unable to archive voucher.'},{status:500})}}
export async function PATCH(_r:NextRequest,{params}:{params:Promise<{id:string}>}){try{const s=await getSession();if(!s)return NextResponse.json({message:'Unauthorized'},{status:401});const id=await idOf(params);if(id===null)return NextResponse.json({message:'Invalid voucher ID.'},{status:400});const rows=await sql`UPDATE vouchers SET deleted_at=NULL,deleted_by=NULL,updated_at=NOW() WHERE voucher_id=${id} AND created_by=${s.userId} AND deleted_at IS NOT NULL RETURNING voucher_id`;if(!rows.length)return NextResponse.json({message:'Archived voucher not found.'},{status:404});return NextResponse.json({success:true,voucherId:Number(rows[0].voucher_id)})}catch(e){console.error(e);return NextResponse.json({message:'Unable to restore voucher.'},{status:500})}}
